### ISSUE TITLE
Can't add subjectaltName

### ISSUE THREAD

**Issue by gunph1ld** [ValdikSS/easy-rsa-ipsec#5]
subjectaltName is required for my implementation, how can I add it?

**Comment by ValdikSS** [comment]
It's added by default to the server and clients' certificates and equals to CN.

**Comment by gunph1ld** [comment]
Hello.

Yes, you are right, sorry, but I see there is only DNS by default.
I found the key `--subject-alt-name` and going use it, thank you.
